DROP TRIGGER IF EXISTS admin_notes_set_updated_at ON admin_notes;
DROP TRIGGER IF EXISTS submission_sessions_set_updated_at ON submission_sessions;
DROP TRIGGER IF EXISTS waitlist_submissions_soft_delete ON waitlist_submissions;
DROP TRIGGER IF EXISTS waitlist_submissions_set_updated_at ON waitlist_submissions;
DROP TRIGGER IF EXISTS team_sizes_set_updated_at ON team_sizes;
DROP TRIGGER IF EXISTS roles_set_updated_at ON roles;
DROP TRIGGER IF EXISTS hiring_frustrations_set_updated_at ON hiring_frustrations;
DROP TRIGGER IF EXISTS hiring_tools_set_updated_at ON hiring_tools;
DROP TRIGGER IF EXISTS industries_set_updated_at ON industries;

DROP TABLE IF EXISTS admin_notes;
DROP TABLE IF EXISTS submission_sessions;
DROP TABLE IF EXISTS submission_frustrations;
DROP TABLE IF EXISTS submission_hiring_tools;
DROP TABLE IF EXISTS submission_industries;
DROP TABLE IF EXISTS waitlist_submissions;
DROP TABLE IF EXISTS team_sizes;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS hiring_frustrations;
DROP TABLE IF EXISTS hiring_tools;
DROP TABLE IF EXISTS industries;
