apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anglehr

resources:
  - namespace.yaml
  - configmap.yaml
  - server/deployment.yaml
  - server/service.yaml
  - email-worker/deployment.yaml
  - upload-worker/deployment.yaml
  - fluvio-ui/deployment.yaml
  - fluvio-ui/service.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: anglehr
    includeSelectors: false

images:
  - name: ghcr.io/angle-hr/server
    newTag: latest
