FROM golang:1.25.10-alpine

RUN apk add --no-cache git ca-certificates wget build-base

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN go build -gcflags="all=-N -l" -o /server ./cmd/server

EXPOSE 8080 2345

ENTRYPOINT ["dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server", "--"]
