// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminNote = `-- name: CreateAdminNote :one
INSERT INTO admin_notes (submission_id, note, created_by)
SELECT ws.id, $2, $3
FROM waitlist_submissions ws
WHERE ws.uuid = $1
  AND ws.deleted_at IS NULL
RETURNING uuid, note, created_by, created_at
`

type CreateAdminNoteParams struct {
	Uuid      uuid.UUID `json:"uuid"`
	Note      string    `json:"note"`
	CreatedBy string    `json:"created_by"`
}

type CreateAdminNoteRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Note      string    `json:"note"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAdminNote(ctx context.Context, arg CreateAdminNoteParams) (CreateAdminNoteRow, error) {
	row := q.db.QueryRow(ctx, createAdminNote, arg.Uuid, arg.Note, arg.CreatedBy)
	var i CreateAdminNoteRow
	err := row.Scan(
		&i.Uuid,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionDetail = `-- name: GetSubmissionDetail :one
SELECT
    ws.id,
    ws.uuid,
    ws.name,
    ws.wants_early_access,
    ws.wants_user_testing,
    ws.submitted_at,
    r.uuid AS role_uuid,
    r.name AS role_name,
    ts.uuid AS team_size_uuid,
    ts.label AS team_size_label
FROM waitlist_submissions ws
INNER JOIN roles r ON r.id = ws.role_id
INNER JOIN team_sizes ts ON ts.id = ws.team_size_id
WHERE ws.uuid = $1
  AND ws.deleted_at IS NULL
`

type GetSubmissionDetailRow struct {
	ID               int64     `json:"id"`
	Uuid             uuid.UUID `json:"uuid"`
	Name             string    `json:"name"`
	WantsEarlyAccess bool      `json:"wants_early_access"`
	WantsUserTesting bool      `json:"wants_user_testing"`
	SubmittedAt      time.Time `json:"submitted_at"`
	RoleUuid         uuid.UUID `json:"role_uuid"`
	RoleName         string    `json:"role_name"`
	TeamSizeUuid     uuid.UUID `json:"team_size_uuid"`
	TeamSizeLabel    string    `json:"team_size_label"`
}

func (q *Queries) GetSubmissionDetail(ctx context.Context, argUuid uuid.UUID) (GetSubmissionDetailRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionDetail, argUuid)
	var i GetSubmissionDetailRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.WantsEarlyAccess,
		&i.WantsUserTesting,
		&i.SubmittedAt,
		&i.RoleUuid,
		&i.RoleName,
		&i.TeamSizeUuid,
		&i.TeamSizeLabel,
	)
	return i, err
}

const getSubmissionInternalID = `-- name: GetSubmissionInternalID :one
SELECT id
FROM waitlist_submissions
WHERE uuid = $1
`

func (q *Queries) GetSubmissionInternalID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSubmissionInternalID, argUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSubmissionStats = `-- name: GetSubmissionStats :one
SELECT
    COUNT(*)::bigint AS total_submissions,
    COALESCE(AVG(CASE WHEN wants_early_access THEN 1.0 ELSE 0.0 END), 0)::float8 AS early_access_opt_in_rate,
    COALESCE(AVG(CASE WHEN wants_user_testing THEN 1.0 ELSE 0.0 END), 0)::float8 AS user_testing_opt_in_rate
FROM waitlist_submissions
WHERE deleted_at IS NULL
`

type GetSubmissionStatsRow struct {
	TotalSubmissions     int64   `json:"total_submissions"`
	EarlyAccessOptInRate float64 `json:"early_access_opt_in_rate"`
	UserTestingOptInRate float64 `json:"user_testing_opt_in_rate"`
}

func (q *Queries) GetSubmissionStats(ctx context.Context) (GetSubmissionStatsRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionStats)
	var i GetSubmissionStatsRow
	err := row.Scan(&i.TotalSubmissions, &i.EarlyAccessOptInRate, &i.UserTestingOptInRate)
	return i, err
}

const listSubmissionFrustrations = `-- name: ListSubmissionFrustrations :many
SELECT hf.uuid, hf.description, sf.other_text, hf.slug
FROM submission_frustrations sf
INNER JOIN hiring_frustrations hf ON hf.id = sf.frustration_id
WHERE sf.submission_id = $1
ORDER BY hf.sort_order, hf.description
`

type ListSubmissionFrustrationsRow struct {
	Uuid        uuid.UUID `json:"uuid"`
	Description string    `json:"description"`
	OtherText   *string   `json:"other_text"`
	Slug        string    `json:"slug"`
}

func (q *Queries) ListSubmissionFrustrations(ctx context.Context, submissionID int64) ([]ListSubmissionFrustrationsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionFrustrations, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionFrustrationsRow{}
	for rows.Next() {
		var i ListSubmissionFrustrationsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Description,
			&i.OtherText,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionHiringTools = `-- name: ListSubmissionHiringTools :many
SELECT ht.uuid, ht.name, sht.other_text, ht.slug
FROM submission_hiring_tools sht
INNER JOIN hiring_tools ht ON ht.id = sht.hiring_tool_id
WHERE sht.submission_id = $1
ORDER BY ht.sort_order, ht.name
`

type ListSubmissionHiringToolsRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	OtherText *string   `json:"other_text"`
	Slug      string    `json:"slug"`
}

func (q *Queries) ListSubmissionHiringTools(ctx context.Context, submissionID int64) ([]ListSubmissionHiringToolsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionHiringTools, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionHiringToolsRow{}
	for rows.Next() {
		var i ListSubmissionHiringToolsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.OtherText,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionIndustries = `-- name: ListSubmissionIndustries :many
SELECT i.uuid, i.name, si.other_text, i.slug
FROM submission_industries si
INNER JOIN industries i ON i.id = si.industry_id
WHERE si.submission_id = $1
ORDER BY i.sort_order, i.name
`

type ListSubmissionIndustriesRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	OtherText *string   `json:"other_text"`
	Slug      string    `json:"slug"`
}

func (q *Queries) ListSubmissionIndustries(ctx context.Context, submissionID int64) ([]ListSubmissionIndustriesRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionIndustries, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionIndustriesRow{}
	for rows.Next() {
		var i ListSubmissionIndustriesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.OtherText,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT
    ws.uuid,
    ws.name,
    ws.wants_early_access,
    ws.wants_user_testing,
    ws.submitted_at,
    r.uuid AS role_uuid,
    r.name AS role_name,
    ts.uuid AS team_size_uuid,
    ts.label AS team_size_label
FROM waitlist_submissions ws
INNER JOIN roles r ON r.id = ws.role_id
INNER JOIN team_sizes ts ON ts.id = ws.team_size_id
WHERE ws.deleted_at IS NULL
  AND (
    $1::uuid IS NULL
    OR EXISTS (
        SELECT 1
        FROM submission_industries si
        INNER JOIN industries i ON i.id = si.industry_id
        WHERE si.submission_id = ws.id
          AND i.uuid = $1::uuid
    )
  )
  AND ($2::uuid IS NULL OR r.uuid = $2::uuid)
  AND ($3::uuid IS NULL OR ts.uuid = $3::uuid)
  AND ($4::boolean IS NULL OR ws.wants_early_access = $4::boolean)
  AND ($5::boolean IS NULL OR ws.wants_user_testing = $5::boolean)
  AND ($6::timestamptz IS NULL OR ws.submitted_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR ws.submitted_at <= $7::timestamptz)
  AND (
    $8::timestamptz IS NULL
    OR $9::bigint IS NULL
    OR (ws.submitted_at, ws.id) < ($8::timestamptz, $9::bigint)
  )
ORDER BY ws.submitted_at DESC, ws.id DESC
LIMIT $10
`

type ListSubmissionsParams struct {
	IndustryUuid      pgtype.UUID        `json:"industry_uuid"`
	RoleUuid          pgtype.UUID        `json:"role_uuid"`
	TeamSizeUuid      pgtype.UUID        `json:"team_size_uuid"`
	WantsEarlyAccess  *bool              `json:"wants_early_access"`
	WantsUserTesting  *bool              `json:"wants_user_testing"`
	SubmittedFrom     pgtype.Timestamptz `json:"submitted_from"`
	SubmittedTo       pgtype.Timestamptz `json:"submitted_to"`
	CursorSubmittedAt pgtype.Timestamptz `json:"cursor_submitted_at"`
	CursorID          *int64             `json:"cursor_id"`
	RowLimit          int32              `json:"row_limit"`
}

type ListSubmissionsRow struct {
	Uuid             uuid.UUID `json:"uuid"`
	Name             string    `json:"name"`
	WantsEarlyAccess bool      `json:"wants_early_access"`
	WantsUserTesting bool      `json:"wants_user_testing"`
	SubmittedAt      time.Time `json:"submitted_at"`
	RoleUuid         uuid.UUID `json:"role_uuid"`
	RoleName         string    `json:"role_name"`
	TeamSizeUuid     uuid.UUID `json:"team_size_uuid"`
	TeamSizeLabel    string    `json:"team_size_label"`
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.IndustryUuid,
		arg.RoleUuid,
		arg.TeamSizeUuid,
		arg.WantsEarlyAccess,
		arg.WantsUserTesting,
		arg.SubmittedFrom,
		arg.SubmittedTo,
		arg.CursorSubmittedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsRow{}
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.WantsEarlyAccess,
			&i.WantsUserTesting,
			&i.SubmittedAt,
			&i.RoleUuid,
			&i.RoleName,
			&i.TeamSizeUuid,
			&i.TeamSizeLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopFrustrations = `-- name: ListTopFrustrations :many
SELECT hf.uuid, hf.description, COUNT(*)::bigint AS count
FROM submission_frustrations sf
INNER JOIN hiring_frustrations hf ON hf.id = sf.frustration_id
INNER JOIN waitlist_submissions ws ON ws.id = sf.submission_id
WHERE ws.deleted_at IS NULL
GROUP BY hf.uuid, hf.description
ORDER BY COUNT(*) DESC, hf.description
LIMIT 5
`

type ListTopFrustrationsRow struct {
	Uuid        uuid.UUID `json:"uuid"`
	Description string    `json:"description"`
	Count       int64     `json:"count"`
}

func (q *Queries) ListTopFrustrations(ctx context.Context) ([]ListTopFrustrationsRow, error) {
	rows, err := q.db.Query(ctx, listTopFrustrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopFrustrationsRow{}
	for rows.Next() {
		var i ListTopFrustrationsRow
		if err := rows.Scan(&i.Uuid, &i.Description, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopIndustries = `-- name: ListTopIndustries :many
SELECT i.uuid, i.name, COUNT(*)::bigint AS count
FROM submission_industries si
INNER JOIN industries i ON i.id = si.industry_id
INNER JOIN waitlist_submissions ws ON ws.id = si.submission_id
WHERE ws.deleted_at IS NULL
GROUP BY i.uuid, i.name
ORDER BY COUNT(*) DESC, i.name
LIMIT 5
`

type ListTopIndustriesRow struct {
	Uuid  uuid.UUID `json:"uuid"`
	Name  string    `json:"name"`
	Count int64     `json:"count"`
}

func (q *Queries) ListTopIndustries(ctx context.Context) ([]ListTopIndustriesRow, error) {
	rows, err := q.db.Query(ctx, listTopIndustries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopIndustriesRow{}
	for rows.Next() {
		var i ListTopIndustriesRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
