// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const hiringFrustrationsReferenceVersion = `-- name: HiringFrustrationsReferenceVersion :one
SELECT COALESCE(MAX(updated_at), to_timestamp(0))::text || ':' || COUNT(*)::text AS version
FROM hiring_frustrations
`

func (q *Queries) HiringFrustrationsReferenceVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, hiringFrustrationsReferenceVersion)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const hiringToolsReferenceVersion = `-- name: HiringToolsReferenceVersion :one
SELECT COALESCE(MAX(updated_at), to_timestamp(0))::text || ':' || COUNT(*)::text AS version
FROM hiring_tools
`

func (q *Queries) HiringToolsReferenceVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, hiringToolsReferenceVersion)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const industriesReferenceVersion = `-- name: IndustriesReferenceVersion :one
SELECT COALESCE(MAX(updated_at), to_timestamp(0))::text || ':' || COUNT(*)::text AS version
FROM industries
`

func (q *Queries) IndustriesReferenceVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, industriesReferenceVersion)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const listHiringFrustrations = `-- name: ListHiringFrustrations :many
SELECT uuid, description, slug, sort_order
FROM hiring_frustrations
WHERE is_active = TRUE
ORDER BY sort_order, description
`

type ListHiringFrustrationsRow struct {
	Uuid        uuid.UUID `json:"uuid"`
	Description string    `json:"description"`
	Slug        string    `json:"slug"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) ListHiringFrustrations(ctx context.Context) ([]ListHiringFrustrationsRow, error) {
	rows, err := q.db.Query(ctx, listHiringFrustrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHiringFrustrationsRow{}
	for rows.Next() {
		var i ListHiringFrustrationsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Description,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiringTools = `-- name: ListHiringTools :many
SELECT uuid, name, slug, COALESCE(icon_key, '') AS icon_key, COALESCE(category, '') AS category, sort_order
FROM hiring_tools
WHERE is_active = TRUE
ORDER BY sort_order, name
`

type ListHiringToolsRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	IconKey   string    `json:"icon_key"`
	Category  string    `json:"category"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) ListHiringTools(ctx context.Context) ([]ListHiringToolsRow, error) {
	rows, err := q.db.Query(ctx, listHiringTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHiringToolsRow{}
	for rows.Next() {
		var i ListHiringToolsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Slug,
			&i.IconKey,
			&i.Category,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndustries = `-- name: ListIndustries :many
SELECT uuid, name, slug, COALESCE(icon_key, '') AS icon_key, sort_order
FROM industries
WHERE is_active = TRUE
ORDER BY sort_order, name
`

type ListIndustriesRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	IconKey   string    `json:"icon_key"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) ListIndustries(ctx context.Context) ([]ListIndustriesRow, error) {
	rows, err := q.db.Query(ctx, listIndustries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIndustriesRow{}
	for rows.Next() {
		var i ListIndustriesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Slug,
			&i.IconKey,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT uuid, name, slug, sort_order
FROM roles
WHERE is_active = TRUE
ORDER BY sort_order, name
`

type ListRolesRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamSizes = `-- name: ListTeamSizes :many
SELECT uuid, label, min_size, max_size, sort_order
FROM team_sizes
ORDER BY sort_order, label
`

type ListTeamSizesRow struct {
	Uuid      uuid.UUID `json:"uuid"`
	Label     string    `json:"label"`
	MinSize   *int32    `json:"min_size"`
	MaxSize   *int32    `json:"max_size"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) ListTeamSizes(ctx context.Context) ([]ListTeamSizesRow, error) {
	rows, err := q.db.Query(ctx, listTeamSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamSizesRow{}
	for rows.Next() {
		var i ListTeamSizesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Label,
			&i.MinSize,
			&i.MaxSize,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFrustrationIDs = `-- name: ResolveFrustrationIDs :many
SELECT id, uuid, slug
FROM hiring_frustrations
WHERE uuid = ANY($1::uuid[])
  AND is_active = TRUE
`

type ResolveFrustrationIDsRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
	Slug string    `json:"slug"`
}

func (q *Queries) ResolveFrustrationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveFrustrationIDsRow, error) {
	rows, err := q.db.Query(ctx, resolveFrustrationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveFrustrationIDsRow{}
	for rows.Next() {
		var i ResolveFrustrationIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveHiringToolIDs = `-- name: ResolveHiringToolIDs :many
SELECT id, uuid, slug
FROM hiring_tools
WHERE uuid = ANY($1::uuid[])
  AND is_active = TRUE
`

type ResolveHiringToolIDsRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
	Slug string    `json:"slug"`
}

func (q *Queries) ResolveHiringToolIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveHiringToolIDsRow, error) {
	rows, err := q.db.Query(ctx, resolveHiringToolIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveHiringToolIDsRow{}
	for rows.Next() {
		var i ResolveHiringToolIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIndustryIDs = `-- name: ResolveIndustryIDs :many
SELECT id, uuid, slug
FROM industries
WHERE uuid = ANY($1::uuid[])
  AND is_active = TRUE
`

type ResolveIndustryIDsRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
	Slug string    `json:"slug"`
}

func (q *Queries) ResolveIndustryIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveIndustryIDsRow, error) {
	rows, err := q.db.Query(ctx, resolveIndustryIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveIndustryIDsRow{}
	for rows.Next() {
		var i ResolveIndustryIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveRoleID = `-- name: ResolveRoleID :one
SELECT id
FROM roles
WHERE uuid = $1
  AND is_active = TRUE
`

func (q *Queries) ResolveRoleID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, resolveRoleID, argUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resolveTeamSizeID = `-- name: ResolveTeamSizeID :one
SELECT id
FROM team_sizes
WHERE uuid = $1
`

func (q *Queries) ResolveTeamSizeID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, resolveTeamSizeID, argUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const rolesReferenceVersion = `-- name: RolesReferenceVersion :one
SELECT COALESCE(MAX(updated_at), to_timestamp(0))::text || ':' || COUNT(*)::text AS version
FROM roles
`

func (q *Queries) RolesReferenceVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, rolesReferenceVersion)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const teamSizesReferenceVersion = `-- name: TeamSizesReferenceVersion :one
SELECT COALESCE(MAX(updated_at), to_timestamp(0))::text || ':' || COUNT(*)::text AS version
FROM team_sizes
`

func (q *Queries) TeamSizesReferenceVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, teamSizesReferenceVersion)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const uUIDForRoleID = `-- name: UUIDForRoleID :one
SELECT uuid
FROM roles
WHERE id = $1
`

func (q *Queries) UUIDForRoleID(ctx context.Context, id int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, uUIDForRoleID, id)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const uUIDForTeamSizeID = `-- name: UUIDForTeamSizeID :one
SELECT uuid
FROM team_sizes
WHERE id = $1
`

func (q *Queries) UUIDForTeamSizeID(ctx context.Context, id int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, uUIDForTeamSizeID, id)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const uUIDsForFrustrationIDs = `-- name: UUIDsForFrustrationIDs :many
SELECT id, uuid
FROM hiring_frustrations
WHERE id = ANY($1::bigint[])
`

type UUIDsForFrustrationIDsRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
}

func (q *Queries) UUIDsForFrustrationIDs(ctx context.Context, dollar_1 []int64) ([]UUIDsForFrustrationIDsRow, error) {
	rows, err := q.db.Query(ctx, uUIDsForFrustrationIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UUIDsForFrustrationIDsRow{}
	for rows.Next() {
		var i UUIDsForFrustrationIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uUIDsForHiringToolIDs = `-- name: UUIDsForHiringToolIDs :many
SELECT id, uuid
FROM hiring_tools
WHERE id = ANY($1::bigint[])
`

type UUIDsForHiringToolIDsRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
}

func (q *Queries) UUIDsForHiringToolIDs(ctx context.Context, dollar_1 []int64) ([]UUIDsForHiringToolIDsRow, error) {
	rows, err := q.db.Query(ctx, uUIDsForHiringToolIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UUIDsForHiringToolIDsRow{}
	for rows.Next() {
		var i UUIDsForHiringToolIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uUIDsForIndustryIDs = `-- name: UUIDsForIndustryIDs :many
SELECT id, uuid
FROM industries
WHERE id = ANY($1::bigint[])
`

type UUIDsForIndustryIDsRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
}

func (q *Queries) UUIDsForIndustryIDs(ctx context.Context, dollar_1 []int64) ([]UUIDsForIndustryIDsRow, error) {
	rows, err := q.db.Query(ctx, uUIDsForIndustryIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UUIDsForIndustryIDsRow{}
	for rows.Next() {
		var i UUIDsForIndustryIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
