// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminNote struct {
	ID           int64     `json:"id"`
	Uuid         uuid.UUID `json:"uuid"`
	SubmissionID int64     `json:"submission_id"`
	Note         string    `json:"note"`
	CreatedBy    string    `json:"created_by"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type HiringFrustration struct {
	ID          int64     `json:"id"`
	Uuid        uuid.UUID `json:"uuid"`
	Description string    `json:"description"`
	Slug        string    `json:"slug"`
	SortOrder   int32     `json:"sort_order"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type HiringTool struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	IconKey   *string   `json:"icon_key"`
	Category  *string   `json:"category"`
	SortOrder int32     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Industry struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	IconKey   *string   `json:"icon_key"`
	SortOrder int32     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	SortOrder int32     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SubmissionFrustration struct {
	SubmissionID  int64   `json:"submission_id"`
	FrustrationID int64   `json:"frustration_id"`
	OtherText     *string `json:"other_text"`
}

type SubmissionHiringTool struct {
	SubmissionID int64   `json:"submission_id"`
	HiringToolID int64   `json:"hiring_tool_id"`
	OtherText    *string `json:"other_text"`
}

type SubmissionIndustry struct {
	SubmissionID int64   `json:"submission_id"`
	IndustryID   int64   `json:"industry_id"`
	OtherText    *string `json:"other_text"`
}

type SubmissionSession struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	TokenHash    []byte             `json:"token_hash"`
	CurrentStep  int16              `json:"current_step"`
	ExpiresAt    time.Time          `json:"expires_at"`
	PartialState []byte             `json:"partial_state"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	SubmissionID *int64             `json:"submission_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type TeamSize struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	Label     string    `json:"label"`
	MinSize   *int32    `json:"min_size"`
	MaxSize   *int32    `json:"max_size"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Waitlist struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	Email       string             `json:"email"`
	CompanyName *string            `json:"company_name"`
	CompanySize *string            `json:"company_size"`
	Role        *string            `json:"role"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type WaitlistSubmission struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	Name             string             `json:"name"`
	WantsEarlyAccess bool               `json:"wants_early_access"`
	WantsUserTesting bool               `json:"wants_user_testing"`
	RoleID           int64              `json:"role_id"`
	TeamSizeID       int64              `json:"team_size_id"`
	SubmittedAt      time.Time          `json:"submitted_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}
