// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteSubmissionSession(ctx context.Context, arg CompleteSubmissionSessionParams) (int64, error)
	CountWaitlistEntries(ctx context.Context) (int64, error)
	CreateAdminNote(ctx context.Context, arg CreateAdminNoteParams) (CreateAdminNoteRow, error)
	CreateSubmissionSession(ctx context.Context, arg CreateSubmissionSessionParams) (CreateSubmissionSessionRow, error)
	GetOtherFrustrationID(ctx context.Context) (int64, error)
	GetOtherHiringToolID(ctx context.Context) (int64, error)
	GetOtherIndustryID(ctx context.Context) (int64, error)
	GetSubmissionDetail(ctx context.Context, argUuid uuid.UUID) (GetSubmissionDetailRow, error)
	GetSubmissionInternalID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	GetSubmissionSessionByToken(ctx context.Context, tokenHash []byte) (GetSubmissionSessionByTokenRow, error)
	GetSubmissionStats(ctx context.Context) (GetSubmissionStatsRow, error)
	HiringFrustrationsReferenceVersion(ctx context.Context) (interface{}, error)
	HiringToolsReferenceVersion(ctx context.Context) (interface{}, error)
	IndustriesReferenceVersion(ctx context.Context) (interface{}, error)
	InsertSubmissionFrustration(ctx context.Context, arg InsertSubmissionFrustrationParams) error
	InsertSubmissionHiringTool(ctx context.Context, arg InsertSubmissionHiringToolParams) error
	InsertSubmissionIndustry(ctx context.Context, arg InsertSubmissionIndustryParams) error
	InsertWaitlistEntry(ctx context.Context, arg InsertWaitlistEntryParams) error
	InsertWaitlistSubmission(ctx context.Context, arg InsertWaitlistSubmissionParams) (InsertWaitlistSubmissionRow, error)
	ListHiringFrustrations(ctx context.Context) ([]ListHiringFrustrationsRow, error)
	ListHiringTools(ctx context.Context) ([]ListHiringToolsRow, error)
	ListIndustries(ctx context.Context) ([]ListIndustriesRow, error)
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListSubmissionFrustrations(ctx context.Context, submissionID int64) ([]ListSubmissionFrustrationsRow, error)
	ListSubmissionHiringTools(ctx context.Context, submissionID int64) ([]ListSubmissionHiringToolsRow, error)
	ListSubmissionIndustries(ctx context.Context, submissionID int64) ([]ListSubmissionIndustriesRow, error)
	ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error)
	ListTeamSizes(ctx context.Context) ([]ListTeamSizesRow, error)
	ListTopFrustrations(ctx context.Context) ([]ListTopFrustrationsRow, error)
	ListTopIndustries(ctx context.Context) ([]ListTopIndustriesRow, error)
	ResolveFrustrationIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveFrustrationIDsRow, error)
	ResolveHiringToolIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveHiringToolIDsRow, error)
	ResolveIndustryIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveIndustryIDsRow, error)
	ResolveRoleID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	ResolveTeamSizeID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	RolesReferenceVersion(ctx context.Context) (interface{}, error)
	TeamSizesReferenceVersion(ctx context.Context) (interface{}, error)
	UUIDForRoleID(ctx context.Context, id int64) (uuid.UUID, error)
	UUIDForTeamSizeID(ctx context.Context, id int64) (uuid.UUID, error)
	UUIDsForFrustrationIDs(ctx context.Context, dollar_1 []int64) ([]UUIDsForFrustrationIDsRow, error)
	UUIDsForHiringToolIDs(ctx context.Context, dollar_1 []int64) ([]UUIDsForHiringToolIDsRow, error)
	UUIDsForIndustryIDs(ctx context.Context, dollar_1 []int64) ([]UUIDsForIndustryIDsRow, error)
	UpdateSubmissionSessionStep(ctx context.Context, arg UpdateSubmissionSessionStepParams) (int64, error)
	WaitlistEmailExists(ctx context.Context, email string) (bool, error)
}

var _ Querier = (*Queries)(nil)
