// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeSubmissionSession = `-- name: CompleteSubmissionSession :execrows
UPDATE submission_sessions
SET completed_at = now(),
    submission_id = $2,
    updated_at = now()
WHERE id = $1
  AND completed_at IS NULL
`

type CompleteSubmissionSessionParams struct {
	ID           int64  `json:"id"`
	SubmissionID *int64 `json:"submission_id"`
}

func (q *Queries) CompleteSubmissionSession(ctx context.Context, arg CompleteSubmissionSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeSubmissionSession, arg.ID, arg.SubmissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSubmissionSession = `-- name: CreateSubmissionSession :one
INSERT INTO submission_sessions (token_hash, current_step, expires_at, partial_state)
VALUES ($1, 1, $2, '{}'::jsonb)
RETURNING id, current_step, expires_at, partial_state, completed_at
`

type CreateSubmissionSessionParams struct {
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreateSubmissionSessionRow struct {
	ID           int64              `json:"id"`
	CurrentStep  int16              `json:"current_step"`
	ExpiresAt    time.Time          `json:"expires_at"`
	PartialState []byte             `json:"partial_state"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateSubmissionSession(ctx context.Context, arg CreateSubmissionSessionParams) (CreateSubmissionSessionRow, error) {
	row := q.db.QueryRow(ctx, createSubmissionSession, arg.TokenHash, arg.ExpiresAt)
	var i CreateSubmissionSessionRow
	err := row.Scan(
		&i.ID,
		&i.CurrentStep,
		&i.ExpiresAt,
		&i.PartialState,
		&i.CompletedAt,
	)
	return i, err
}

const getOtherFrustrationID = `-- name: GetOtherFrustrationID :one
SELECT id
FROM hiring_frustrations
WHERE slug = 'other'
`

func (q *Queries) GetOtherFrustrationID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOtherFrustrationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOtherHiringToolID = `-- name: GetOtherHiringToolID :one
SELECT id
FROM hiring_tools
WHERE slug = 'other'
`

func (q *Queries) GetOtherHiringToolID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOtherHiringToolID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOtherIndustryID = `-- name: GetOtherIndustryID :one
SELECT id
FROM industries
WHERE slug = 'other'
`

func (q *Queries) GetOtherIndustryID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOtherIndustryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSubmissionSessionByToken = `-- name: GetSubmissionSessionByToken :one
SELECT id, current_step, expires_at, partial_state, completed_at
FROM submission_sessions
WHERE token_hash = $1
`

type GetSubmissionSessionByTokenRow struct {
	ID           int64              `json:"id"`
	CurrentStep  int16              `json:"current_step"`
	ExpiresAt    time.Time          `json:"expires_at"`
	PartialState []byte             `json:"partial_state"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetSubmissionSessionByToken(ctx context.Context, tokenHash []byte) (GetSubmissionSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionSessionByToken, tokenHash)
	var i GetSubmissionSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.CurrentStep,
		&i.ExpiresAt,
		&i.PartialState,
		&i.CompletedAt,
	)
	return i, err
}

const insertSubmissionFrustration = `-- name: InsertSubmissionFrustration :exec
INSERT INTO submission_frustrations (submission_id, frustration_id, other_text)
VALUES ($1, $2, $3)
`

type InsertSubmissionFrustrationParams struct {
	SubmissionID  int64   `json:"submission_id"`
	FrustrationID int64   `json:"frustration_id"`
	OtherText     *string `json:"other_text"`
}

func (q *Queries) InsertSubmissionFrustration(ctx context.Context, arg InsertSubmissionFrustrationParams) error {
	_, err := q.db.Exec(ctx, insertSubmissionFrustration, arg.SubmissionID, arg.FrustrationID, arg.OtherText)
	return err
}

const insertSubmissionHiringTool = `-- name: InsertSubmissionHiringTool :exec
INSERT INTO submission_hiring_tools (submission_id, hiring_tool_id, other_text)
VALUES ($1, $2, $3)
`

type InsertSubmissionHiringToolParams struct {
	SubmissionID int64   `json:"submission_id"`
	HiringToolID int64   `json:"hiring_tool_id"`
	OtherText    *string `json:"other_text"`
}

func (q *Queries) InsertSubmissionHiringTool(ctx context.Context, arg InsertSubmissionHiringToolParams) error {
	_, err := q.db.Exec(ctx, insertSubmissionHiringTool, arg.SubmissionID, arg.HiringToolID, arg.OtherText)
	return err
}

const insertSubmissionIndustry = `-- name: InsertSubmissionIndustry :exec
INSERT INTO submission_industries (submission_id, industry_id, other_text)
VALUES ($1, $2, $3)
`

type InsertSubmissionIndustryParams struct {
	SubmissionID int64   `json:"submission_id"`
	IndustryID   int64   `json:"industry_id"`
	OtherText    *string `json:"other_text"`
}

func (q *Queries) InsertSubmissionIndustry(ctx context.Context, arg InsertSubmissionIndustryParams) error {
	_, err := q.db.Exec(ctx, insertSubmissionIndustry, arg.SubmissionID, arg.IndustryID, arg.OtherText)
	return err
}

const insertWaitlistSubmission = `-- name: InsertWaitlistSubmission :one
INSERT INTO waitlist_submissions (
    name, wants_early_access, wants_user_testing, role_id, team_size_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, submitted_at
`

type InsertWaitlistSubmissionParams struct {
	Name             string `json:"name"`
	WantsEarlyAccess bool   `json:"wants_early_access"`
	WantsUserTesting bool   `json:"wants_user_testing"`
	RoleID           int64  `json:"role_id"`
	TeamSizeID       int64  `json:"team_size_id"`
}

type InsertWaitlistSubmissionRow struct {
	ID          int64     `json:"id"`
	Uuid        uuid.UUID `json:"uuid"`
	SubmittedAt time.Time `json:"submitted_at"`
}

func (q *Queries) InsertWaitlistSubmission(ctx context.Context, arg InsertWaitlistSubmissionParams) (InsertWaitlistSubmissionRow, error) {
	row := q.db.QueryRow(ctx, insertWaitlistSubmission,
		arg.Name,
		arg.WantsEarlyAccess,
		arg.WantsUserTesting,
		arg.RoleID,
		arg.TeamSizeID,
	)
	var i InsertWaitlistSubmissionRow
	err := row.Scan(&i.ID, &i.Uuid, &i.SubmittedAt)
	return i, err
}

const updateSubmissionSessionStep = `-- name: UpdateSubmissionSessionStep :execrows
UPDATE submission_sessions
SET partial_state = $2::jsonb,
    current_step = $3,
    updated_at = now()
WHERE id = $1
  AND completed_at IS NULL
`

type UpdateSubmissionSessionStepParams struct {
	ID          int64  `json:"id"`
	Column2     []byte `json:"column_2"`
	CurrentStep int16  `json:"current_step"`
}

func (q *Queries) UpdateSubmissionSessionStep(ctx context.Context, arg UpdateSubmissionSessionStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSubmissionSessionStep, arg.ID, arg.Column2, arg.CurrentStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
