// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: waitlist.sql

package sqlc

import (
	"context"
)

const countWaitlistEntries = `-- name: CountWaitlistEntries :one
SELECT COUNT(*)::bigint
FROM waitlist
WHERE deleted_at IS NULL
`

func (q *Queries) CountWaitlistEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistEntries)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertWaitlistEntry = `-- name: InsertWaitlistEntry :exec
INSERT INTO waitlist (email, company_name, company_size, role)
VALUES ($1, $2, $3, $4)
`

type InsertWaitlistEntryParams struct {
	Email       string  `json:"email"`
	CompanyName *string `json:"company_name"`
	CompanySize *string `json:"company_size"`
	Role        *string `json:"role"`
}

func (q *Queries) InsertWaitlistEntry(ctx context.Context, arg InsertWaitlistEntryParams) error {
	_, err := q.db.Exec(ctx, insertWaitlistEntry,
		arg.Email,
		arg.CompanyName,
		arg.CompanySize,
		arg.Role,
	)
	return err
}

const waitlistEmailExists = `-- name: WaitlistEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM waitlist
    WHERE email = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) WaitlistEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, waitlistEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
