apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anglehr
  labels:
    app.kubernetes.io/part-of: anglehr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.example.com
        - fluvio.example.com
      secretName: anglehr-tls
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 8080
    - host: fluvio.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fluvio-ui
                port:
                  number: 80
