apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml

patches:
  - path: configmap.yaml
  - path: server-patch.yaml
  - path: email-worker-patch.yaml

images:
  - name: ghcr.io/angle-hr/server
    newTag: latest
  - name: ghcr.io/angle-hr/server-email-worker
    newTag: latest
  - name: ghcr.io/angle-hr/server-upload-worker
    newTag: latest
  - name: ghcr.io/software78/fluvio_ui
    newTag: "1.0.1"
