-- Default role -> permission matrix from the Roles and permissions doc (Oct 2026).
-- Permissions that are denied for every role (job.delete.hard, form.ask_pay_history,
-- form.edi.view_named) are deliberately absent: there is no grant to revoke.

-- +goose Up
-- +goose StatementBegin
INSERT INTO rbac.role_permissions (role, permission) VALUES
    ('founder', 'job.create'),
    ('hr_1', 'job.create'),
    ('hr_2', 'job.create'),
    ('founder', 'job.requisition.raise'),
    ('hr_1', 'job.requisition.raise'),
    ('hr_2', 'job.requisition.raise'),
    ('line_manager', 'job.requisition.raise'),
    ('founder', 'job.view.all'),
    ('hr_1', 'job.view.all'),
    ('hr_2', 'job.view.all'),
    ('legal', 'job.view.all'),
    ('founder', 'job.view.assigned'),
    ('hr_1', 'job.view.assigned'),
    ('hr_2', 'job.view.assigned'),
    ('line_manager', 'job.view.assigned'),
    ('legal', 'job.view.assigned'),
    ('founder', 'job.view.published_internal'),
    ('hr_1', 'job.view.published_internal'),
    ('hr_2', 'job.view.published_internal'),
    ('line_manager', 'job.view.published_internal'),
    ('payroll', 'job.view.published_internal'),
    ('employee', 'job.view.published_internal'),
    ('legal', 'job.view.published_internal'),
    ('founder', 'job.edit.draft'),
    ('hr_1', 'job.edit.draft'),
    ('hr_2', 'job.edit.draft'),
    ('founder', 'job.edit.published'),
    ('hr_1', 'job.edit.published'),
    ('founder', 'job.template.use'),
    ('hr_1', 'job.template.use'),
    ('hr_2', 'job.template.use'),
    ('founder', 'job.template.create'),
    ('hr_1', 'job.template.create'),
    ('founder', 'job.salary_range.set'),
    ('hr_1', 'job.salary_range.set'),
    ('payroll', 'job.salary_range.set'),
    ('founder', 'job.salary_range.view'),
    ('hr_1', 'job.salary_range.view'),
    ('hr_2', 'job.salary_range.view'),
    ('line_manager', 'job.salary_range.view'),
    ('payroll', 'job.salary_range.view'),
    ('legal', 'job.salary_range.view'),
    ('founder', 'job.budget.approve'),
    ('payroll', 'job.budget.approve'),
    ('founder', 'job.jurisdiction.set'),
    ('hr_1', 'job.jurisdiction.set'),
    ('legal', 'job.jurisdiction.set'),
    ('founder', 'job.approve'),
    ('hr_1', 'job.approve'),
    ('founder', 'job.publish.external'),
    ('hr_1', 'job.publish.external'),
    ('founder', 'job.archive'),
    ('hr_1', 'job.archive'),
    ('founder', 'form.edit.standard_fields'),
    ('hr_1', 'form.edit.standard_fields'),
    ('hr_2', 'form.edit.standard_fields'),
    ('founder', 'form.field.add_custom'),
    ('hr_1', 'form.field.add_custom'),
    ('hr_2', 'form.field.add_custom'),
    ('founder', 'form.field.mark_required'),
    ('hr_1', 'form.field.mark_required'),
    ('hr_2', 'form.field.mark_required'),
    ('legal', 'form.edi_module.enable'),
    ('founder', 'form.edi.view_aggregate'),
    ('legal', 'form.edi.view_aggregate'),
    ('founder', 'form.adjustments.enable'),
    ('hr_1', 'form.adjustments.enable'),
    ('legal', 'form.adjustments.enable'),
    ('founder', 'form.adjustments.view_operational'),
    ('hr_1', 'form.adjustments.view_operational'),
    ('hr_2', 'form.adjustments.view_operational'),
    ('line_manager', 'form.adjustments.view_operational'),
    ('legal', 'form.adjustments.view_operational'),
    ('legal', 'form.adjustments.view_health'),
    ('legal', 'form.health_question.add'),
    ('legal', 'form.vetting.enable'),
    ('legal', 'form.automated_screening.enable'),
    ('founder', 'form.privacy_notice.generate'),
    ('hr_1', 'form.privacy_notice.generate'),
    ('legal', 'form.privacy_notice.generate'),
    ('founder', 'job.collaborator.add'),
    ('hr_1', 'job.collaborator.add'),
    ('hr_2', 'job.collaborator.add'),
    ('founder', 'job.collaborator.add_restricted'),
    ('hr_1', 'job.collaborator.add_restricted'),
    ('legal', 'job.collaborator.add_restricted'),
    ('founder', 'job.role.assign'),
    ('hr_1', 'job.role.assign'),
    ('founder', 'job.access.view_list'),
    ('hr_1', 'job.access.view_list'),
    ('hr_2', 'job.access.view_list'),
    ('line_manager', 'job.access.view_list'),
    ('legal', 'job.access.view_list'),
    ('founder', 'job.share.internal'),
    ('hr_1', 'job.share.internal'),
    ('hr_2', 'job.share.internal'),
    ('founder', 'job.share.external_link'),
    ('hr_1', 'job.share.external_link'),
    ('hr_2', 'job.share.external_link'),
    ('founder', 'job.share.job_board'),
    ('hr_1', 'job.share.job_board'),
    ('founder', 'job.share.referral'),
    ('hr_1', 'job.share.referral'),
    ('hr_2', 'job.share.referral'),
    ('line_manager', 'job.share.referral'),
    ('payroll', 'job.share.referral'),
    ('employee', 'job.share.referral'),
    ('founder', 'job.audit.view'),
    ('legal', 'job.audit.view'),
    ('legal', 'job.retention.set'),
    ('founder', 'job.residency.region.set'),
    ('legal', 'job.residency.region.set');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM rbac.role_permissions;
-- +goose StatementEnd
