-- Starter skills catalogue so /hiring/skills has something to search. Names can be edited or extended in data.
-- +goose Up
-- +goose StatementBegin
INSERT INTO hiring.skills (slug, name) VALUES
    ('accounting', 'Accounting'),
    ('administrative-support', 'Administrative Support'),
    ('agile-methodologies', 'Agile Methodologies'),
    ('analytics', 'Analytics'),
    ('android-development', 'Android Development'),
    ('angular', 'Angular'),
    ('api-design', 'API Design'),
    ('applicant-tracking', 'Applicant Tracking'),
    ('aws', 'AWS'),
    ('azure', 'Azure'),
    ('backend-development', 'Backend Development'),
    ('bookkeeping', 'Bookkeeping'),
    ('brand-management', 'Brand Management'),
    ('budgeting', 'Budgeting'),
    ('business-analysis', 'Business Analysis'),
    ('business-development', 'Business Development'),
    ('c-sharp', 'C#'),
    ('cplusplus', 'C++'),
    ('candidate-sourcing', 'Candidate Sourcing'),
    ('cloud-computing', 'Cloud Computing'),
    ('coaching', 'Coaching'),
    ('communication', 'Communication'),
    ('compliance', 'Compliance'),
    ('conflict-resolution', 'Conflict Resolution'),
    ('content-marketing', 'Content Marketing'),
    ('content-writing', 'Content Writing'),
    ('contract-negotiation', 'Contract Negotiation'),
    ('copywriting', 'Copywriting'),
    ('crm', 'CRM'),
    ('customer-service', 'Customer Service'),
    ('customer-success', 'Customer Success'),
    ('cybersecurity', 'Cybersecurity'),
    ('data-analysis', 'Data Analysis'),
    ('data-engineering', 'Data Engineering'),
    ('data-entry', 'Data Entry'),
    ('data-science', 'Data Science'),
    ('data-visualization', 'Data Visualization'),
    ('databases', 'Databases'),
    ('devops', 'DevOps'),
    ('digital-marketing', 'Digital Marketing'),
    ('docker', 'Docker'),
    ('email-marketing', 'Email Marketing'),
    ('employee-relations', 'Employee Relations'),
    ('excel', 'Excel'),
    ('figma', 'Figma'),
    ('financial-modelling', 'Financial Modelling'),
    ('financial-reporting', 'Financial Reporting'),
    ('forecasting', 'Forecasting'),
    ('frontend-development', 'Frontend Development'),
    ('full-stack-development', 'Full Stack Development'),
    ('go', 'Go'),
    ('google-analytics', 'Google Analytics'),
    ('graphic-design', 'Graphic Design'),
    ('hr-administration', 'HR Administration'),
    ('html-and-css', 'HTML and CSS'),
    ('interviewing', 'Interviewing'),
    ('ios-development', 'iOS Development'),
    ('java', 'Java'),
    ('javascript', 'JavaScript'),
    ('kubernetes', 'Kubernetes'),
    ('leadership', 'Leadership'),
    ('legal-research', 'Legal Research'),
    ('machine-learning', 'Machine Learning'),
    ('market-research', 'Market Research'),
    ('marketing-strategy', 'Marketing Strategy'),
    ('microsoft-office', 'Microsoft Office'),
    ('mobile-development', 'Mobile Development'),
    ('negotiation', 'Negotiation'),
    ('network-administration', 'Network Administration'),
    ('nodejs', 'Node.js'),
    ('onboarding', 'Onboarding'),
    ('operations-management', 'Operations Management'),
    ('payroll', 'Payroll'),
    ('people-management', 'People Management'),
    ('performance-management', 'Performance Management'),
    ('postgresql', 'PostgreSQL'),
    ('presentation-skills', 'Presentation Skills'),
    ('product-management', 'Product Management'),
    ('product-marketing', 'Product Marketing'),
    ('project-management', 'Project Management'),
    ('public-speaking', 'Public Speaking'),
    ('python', 'Python'),
    ('qa-testing', 'QA Testing'),
    ('react', 'React'),
    ('recruiting', 'Recruiting'),
    ('recruitment-marketing', 'Recruitment Marketing'),
    ('relationship-building', 'Relationship Building'),
    ('reporting', 'Reporting'),
    ('sales', 'Sales'),
    ('salesforce', 'Salesforce'),
    ('seo', 'SEO'),
    ('social-media', 'Social Media'),
    ('sql', 'SQL'),
    ('strategic-planning', 'Strategic Planning'),
    ('swift', 'Swift'),
    ('talent-acquisition', 'Talent Acquisition'),
    ('team-leadership', 'Team Leadership'),
    ('technical-writing', 'Technical Writing'),
    ('terraform', 'Terraform'),
    ('time-management', 'Time Management'),
    ('typescript', 'TypeScript'),
    ('ui-design', 'UI Design'),
    ('ux-design', 'UX Design'),
    ('ux-research', 'UX Research'),
    ('vendor-management', 'Vendor Management'),
    ('video-editing', 'Video Editing'),
    ('workforce-planning', 'Workforce Planning'),
    ('written-communication', 'Written Communication')
ON CONFLICT (slug) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM hiring.skills WHERE slug IN (SELECT slug FROM (VALUES
('accounting'),('administrative-support'),('agile-methodologies'),('analytics'),('android-development'),('angular'),('api-design'),('applicant-tracking'),('aws'),('azure'),('backend-development'),('bookkeeping'),('brand-management'),('budgeting'),('business-analysis'),('business-development'),('c-sharp'),('cplusplus'),('candidate-sourcing'),('cloud-computing'),('coaching'),('communication'),('compliance'),('conflict-resolution'),('content-marketing'),('content-writing'),('contract-negotiation'),('copywriting'),('crm'),('customer-service'),('customer-success'),('cybersecurity'),('data-analysis'),('data-engineering'),('data-entry'),('data-science'),('data-visualization'),('databases'),('devops'),('digital-marketing'),('docker'),('email-marketing'),('employee-relations'),('excel'),('figma'),('financial-modelling'),('financial-reporting'),('forecasting'),('frontend-development'),('full-stack-development'),('go'),('google-analytics'),('graphic-design'),('hr-administration'),('html-and-css'),('interviewing'),('ios-development'),('java'),('javascript'),('kubernetes'),('leadership'),('legal-research'),('machine-learning'),('market-research'),('marketing-strategy'),('microsoft-office'),('mobile-development'),('negotiation'),('network-administration'),('nodejs'),('onboarding'),('operations-management'),('payroll'),('people-management'),('performance-management'),('postgresql'),('presentation-skills'),('product-management'),('product-marketing'),('project-management'),('public-speaking'),('python'),('qa-testing'),('react'),('recruiting'),('recruitment-marketing'),('relationship-building'),('reporting'),('sales'),('salesforce'),('seo'),('social-media'),('sql'),('strategic-planning'),('swift'),('talent-acquisition'),('team-leadership'),('technical-writing'),('terraform'),('time-management'),('typescript'),('ui-design'),('ux-design'),('ux-research'),('vendor-management'),('video-editing'),('workforce-planning'),('written-communication')) AS v(slug));
-- +goose StatementEnd
