// Package spec Code generated by swaggo/swag. DO NOT EDIT
package spec

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns aggregate waitlist submission statistics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get submission stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.StatsEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/admin/submissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a cursor-paginated list of waitlist submissions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List submissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (1-100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by industry UUID",
                        "name": "industry_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by role UUID",
                        "name": "role_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by team size UUID",
                        "name": "team_size_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by early access opt-in",
                        "name": "wants_early_access",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by user testing opt-in",
                        "name": "wants_user_testing",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter from timestamp (RFC3339)",
                        "name": "submitted_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to timestamp (RFC3339)",
                        "name": "submitted_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.SubmissionListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/admin/submissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a full waitlist submission by public ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get submission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Submission public ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.SubmissionDetailEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/admin/submissions/{id}/notes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds an internal admin note to a submission.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create submission note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Submission public ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Note payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreateNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.NoteEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/hiring-frustrations": {
            "get": {
                "description": "Returns active hiring frustration options for onboarding step 3.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List hiring frustrations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.HiringFrustrationListEnvelope"
                        }
                    },
                    "304": {
                        "description": "Not Modified"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/hiring-tools": {
            "get": {
                "description": "Returns active hiring tool options for onboarding step 2.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List hiring tools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.HiringToolListEnvelope"
                        }
                    },
                    "304": {
                        "description": "Not Modified"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/industries": {
            "get": {
                "description": "Returns active industry options for onboarding step 1.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List industries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.IndustryListEnvelope"
                        }
                    },
                    "304": {
                        "description": "Not Modified"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "description": "Returns active role options for onboarding step 4.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.RoleListEnvelope"
                        }
                    },
                    "304": {
                        "description": "Not Modified"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/team-sizes": {
            "get": {
                "description": "Returns active team size options for onboarding step 4.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List team sizes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.TeamSizeListEnvelope"
                        }
                    },
                    "304": {
                        "description": "Not Modified"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session": {
            "post": {
                "description": "Starts a new waitlist onboarding session and returns a session token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Create onboarding session",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/session.CreateSessionEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session/{token}": {
            "get": {
                "description": "Returns the current step and saved partial progress for a session token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get onboarding session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.GetSessionEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session/{token}/step/1": {
            "patch": {
                "description": "Saves industry selections for the onboarding session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Save step 1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Step 1 payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.Step1Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.StepProgressEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session/{token}/step/2": {
            "patch": {
                "description": "Saves hiring tool selections for the onboarding session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Save step 2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Step 2 payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.Step2Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.StepProgressEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session/{token}/step/3": {
            "patch": {
                "description": "Saves hiring frustration selections for the onboarding session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Save step 3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Step 3 payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.Step3Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.StepProgressEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session/{token}/step/4": {
            "patch": {
                "description": "Saves role and team size selections for the onboarding session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Save step 4",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Step 4 payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.Step4Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.StepProgressEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist/session/{token}/submit": {
            "post": {
                "description": "Finalizes the onboarding flow and creates a waitlist submission.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Submit onboarding session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Submit payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.SubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/session.SubmitEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.CountDescription": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "admin.CountRef": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "admin.CreateNoteRequest": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "admin.Detail": {
            "type": "object",
            "properties": {
                "frustrations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.NamedRef"
                    }
                },
                "id": {
                    "type": "string"
                },
                "industries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.NamedRef"
                    }
                },
                "name": {
                    "type": "string"
                },
                "other_frustration": {
                    "type": "string"
                },
                "other_industry": {
                    "type": "string"
                },
                "other_tool": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/admin.NamedRef"
                },
                "submitted_at": {
                    "type": "string"
                },
                "team_size": {
                    "$ref": "#/definitions/admin.LabelRef"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.NamedRef"
                    }
                },
                "wants_early_access": {
                    "type": "boolean"
                },
                "wants_user_testing": {
                    "type": "boolean"
                }
            }
        },
        "admin.LabelRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "admin.NamedRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "admin.Note": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "admin.NoteEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/admin.Note"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "admin.Stats": {
            "type": "object",
            "properties": {
                "early_access_opt_in_rate": {
                    "type": "number"
                },
                "top_frustrations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.CountDescription"
                    }
                },
                "top_industries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.CountRef"
                    }
                },
                "total_submissions": {
                    "type": "integer"
                },
                "user_testing_opt_in_rate": {
                    "type": "number"
                }
            }
        },
        "admin.StatsEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/admin.Stats"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "admin.SubmissionDetailEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/admin.Detail"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "admin.SubmissionListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.Summary"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/admin.SubmissionMeta"
                }
            }
        },
        "admin.SubmissionMeta": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "admin.Summary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/admin.NamedRef"
                },
                "submitted_at": {
                    "type": "string"
                },
                "team_size": {
                    "$ref": "#/definitions/admin.LabelRef"
                },
                "wants_early_access": {
                    "type": "boolean"
                },
                "wants_user_testing": {
                    "type": "boolean"
                }
            }
        },
        "apidoc.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "apidoc.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/apidoc.ErrorBody"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "apidoc.Meta": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string",
                    "example": "abc123"
                }
            }
        },
        "catalog.HiringFrustration": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "catalog.HiringFrustrationListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.HiringFrustration"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "catalog.HiringTool": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "catalog.HiringToolListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.HiringTool"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "catalog.Industry": {
            "type": "object",
            "properties": {
                "icon_key": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "catalog.IndustryListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.Industry"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "catalog.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "catalog.RoleListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.Role"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "catalog.TeamSize": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "max_size": {
                    "type": "integer"
                },
                "min_size": {
                    "type": "integer"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "catalog.TeamSizeListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.TeamSize"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "session.CreateSessionData": {
            "type": "object",
            "properties": {
                "current_step": {
                    "type": "integer",
                    "example": 1
                },
                "expires_at": {
                    "type": "string"
                },
                "session_token": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "session.CreateSessionEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/session.CreateSessionData"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "session.GetSessionData": {
            "type": "object",
            "properties": {
                "current_step": {
                    "type": "integer",
                    "example": 2
                },
                "partial": {
                    "$ref": "#/definitions/session.PartialResponse"
                }
            }
        },
        "session.GetSessionEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/session.GetSessionData"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "session.PartialResponse": {
            "type": "object",
            "properties": {
                "frustration_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "industry_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "other_frustration": {
                    "type": "string"
                },
                "other_industry": {
                    "type": "string"
                },
                "other_tool": {
                    "type": "string"
                },
                "role_id": {
                    "type": "string"
                },
                "team_size_id": {
                    "type": "string"
                },
                "tool_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "session.Step1Request": {
            "type": "object",
            "properties": {
                "industry_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "other_industry": {
                    "type": "string"
                }
            }
        },
        "session.Step2Request": {
            "type": "object",
            "properties": {
                "other_tool": {
                    "type": "string"
                },
                "tool_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "session.Step3Request": {
            "type": "object",
            "properties": {
                "frustration_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "other_frustration": {
                    "type": "string"
                }
            }
        },
        "session.Step4Request": {
            "type": "object",
            "properties": {
                "role_id": {
                    "type": "string"
                },
                "team_size_id": {
                    "type": "string"
                }
            }
        },
        "session.StepProgressData": {
            "type": "object",
            "properties": {
                "current_step": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "session.StepProgressEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/session.StepProgressData"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "session.SubmitEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/session.SubmitResponse"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "session.SubmitRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "wants_early_access": {
                    "type": "boolean"
                },
                "wants_user_testing": {
                    "type": "boolean"
                }
            }
        },
        "session.SubmitResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token containing the admin scope",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Angle HR Waitlist API",
	Description:      "Onboarding waitlist and admin API for Angle HR.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
