// Package spec Code generated by swaggo/swag. DO NOT EDIT
package spec

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/countries": {
            "get": {
                "description": "Returns active countries for the waitlist region dropdown.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "countries"
                ],
                "summary": "List countries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CountriesEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/waitlist": {
            "post": {
                "description": "Registers a user for the regional waitlist and global users registry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "waitlist"
                ],
                "summary": "Join waitlist",
                "parameters": [
                    {
                        "description": "Signup payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.SignupEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apidoc.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "apidoc.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/apidoc.ErrorBody"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "apidoc.Meta": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string",
                    "example": "abc123"
                }
            }
        },
        "handler.CountriesEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.CountryResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "handler.CountryResponse": {
            "type": "object",
            "properties": {
                "icon_key": {
                    "type": "string",
                    "example": "flag-uk"
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-4789-a012-3456789abcde"
                },
                "name": {
                    "type": "string",
                    "example": "United Kingdom"
                },
                "region": {
                    "type": "string",
                    "enum": [
                        "uk",
                        "us",
                        "africa",
                        "eu"
                    ],
                    "example": "uk"
                },
                "slug": {
                    "type": "string",
                    "example": "united-kingdom"
                }
            }
        },
        "handler.SignupData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "You're on the list!"
                },
                "region": {
                    "type": "string",
                    "example": "uk"
                }
            }
        },
        "handler.SignupEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.SignupData"
                },
                "meta": {
                    "$ref": "#/definitions/apidoc.Meta"
                }
            }
        },
        "handler.SignupRequest": {
            "type": "object",
            "properties": {
                "country_id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-4789-a012-3456789abcde"
                },
                "email": {
                    "type": "string",
                    "example": "jerry@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Jerry"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Angle HR Waitlist API",
	Description:      "Waitlist signup API for Open HR.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
